//
// Created by igor on 2024.07.06..
//

#ifndef RAYLIB_GAME_TEMPLATE_PLAYEREFFECT_H
#define RAYLIB_GAME_TEMPLATE_PLAYEREFFECT_H

typedef enum {
    MORE_PLAYER_SPEED,
    MORE_BULLET_SPEED,
    SMALLER_BODY,
    LESS_RANDOM_BULLET_SPREAD,
    MORE_MAX_HEALTH,
    LESS_FRICTION,
    SHORTER_SHOOT_COOLDOWN_TIME,
    EVERYONE_GETS_RANDOM_BUFFS,
} PlayerEffectBuffs;

typedef enum {
    LESS_PLAYER_SPEED,
    LESS_BULLET_SPEED,
    LARGER_BODY,
    MORE_RANDOM_BULLET_SPREAD,
    LESS_MAX_HEALTH,
    MORE_FRICTION,
    LONGER_SHOOT_COOLDOWN_TIME,
    EVERYONE_GETS_RANDOM_DEBUFFS,
} PlayerEffectDeBuffs;

#endif //RAYLIB_GAME_TEMPLATE_PLAYEREFFECT_H
